apiVersion: v1
kind: Secret
metadata:
    name: azuredns-config
    namespace: cert-manager
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:kD8WhTfnG/yAwrgsWIJirfSrlrs92pvoA7QlP4HprAoI5Y7OH1V2lA==,iv:cMsptk5j22PNza5GGTHdAe/GM9mqA/0sVPdHebrnSjA=,tag:33br5dRrL1Fex4Rjxe8zUQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMks5ZXJJNXBTSTVlaFlH
            V3hJaUlybzlvNkNPU1BLblBYaHc2cnJJb3hnCmxueGI0c1k2TUgwM011SXh5cUhs
            R3NSajhmSmNEZTFFS1dYa2JvK2xaYncKLS0tIHgyMXNOTXk2V1BYUWtZREhUUWJK
            N25QZWFsZUs1WEQ4ZlF0TXNEcG9VV2sKY8UiVxdiIGAGmH/EbSPxjKmNWSwmIhGe
            Yqr2D2VdGTcT9A9IBhVyCYAYu6dx0Df8rjN2wtyWrbcvVVw2sPDoFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1uuw3lkwaay3mf7qq0rapwnc4yqw439ajj28w8ujde0hd7x5ssufs5fvmjy
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T04:12:52Z"
    mac: ENC[AES256_GCM,data:UXIpSCEm3Kh7tGMGf5p9JdCpkgQ4Upxivw8cRYh4e9oBqZh3ktnNt0VnBmzSu/qabdZj0QDUOfrMUFi/GmzFx3JgqFNv0qOPAui/0jMnVgmhPJoP0dgLZjz51Xj/+3m/Ywd1db0NTx4mLgyuZzB5RwaRrlduyhqaXGcaqALiCcs=,iv:8x63U8zmIoVEe1jIC+Xi5r5OPLv2g1jQFB+ciqMhWC4=,tag:gr/h1FtvLxMteuKcKHQkcA==,type:str]
    version: 3.13.3
